/* Emits what hh_site_builder needs from this folder, so nothing is copied by hand.

     node to-builder.mjs catalogue   two TEMPLATES entries for src/themes/catalogue.js
     node to-builder.mjs seed        supabase/seed-manikanta.sql (upsert of site.json)

   See integrate.md for where each goes. */
import { readFileSync } from 'node:fs';

const here = (f) => readFileSync(new URL(f, import.meta.url), 'utf8');
const MARK = '/* ---- template css ---- */';

const META = {
  'theme-a.css': {
    category: 'retail', key: 'polam-paper', name: 'Polam Paper',
    description: 'Morning field — warm paper, leaf green and turmeric, serif Telugu, arch and rounded frames, a faint line-art backdrop of leaves, millet and spices. Organic and natural stores, millets, Ayurveda, dairy, honey.'
  },
  'theme-b.css': {
    category: 'retail', key: 'vanam-grove', name: 'Vanam Grove',
    description: 'Sunlit grove — mid forest-green gradients with brass rules and medallions, a printed bill-of-fare list, line-art backdrop of leaves and Ayurveda motifs. Organic and natural stores, Ayurveda, herbal and cow-based products.'
  }
};

function template(file) {
  const src = here(file);
  const root = src.match(/:root \{([^}]*)\}/)[1];
  const tokens = Object.fromEntries(
    [...root.matchAll(/--([\w-]+):([^;]+);/g)].map(([, k, v]) => [k, v.trim().replace(/^'|'$/g, '')])
  );
  const css = src.slice(src.indexOf(MARK) + MARK.length).trim();
  // the css goes inside a JS template literal
  if (/[`\\]|\$\{/.test(css)) throw new Error(`${file}: css contains \` \\ or \${`);
  return { ...META[file], tokens, css };
}

const mode = process.argv[2];
if (mode === 'catalogue') {
  for (const file of Object.keys(META)) {
    const t = template(file);
    console.log(`  {
    category: '${t.category}',
    key: '${t.key}',
    name: '${t.name}',
    description: ${JSON.stringify(t.description)},
    tokens: ${JSON.stringify(t.tokens, null, 6).replace(/\n\}$/, '\n    }')},
    css: \`${t.css}\`
  },`);
  }
} else if (mode === 'seed') {
  const site = JSON.parse(here('site.json'));
  const json = JSON.stringify(site.config, null, 2);
  if (json.includes('$json$')) throw new Error('config contains the $json$ quote tag');
  const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
  console.log(`-- Manikanta Naturals as a framework site. Generated by ../manikanta/to-builder.mjs
-- from site.json; edit that, not this. Run AFTER supabase/templates.sql.
-- Safe to re-run: upserts by slug. Left UNPUBLISHED — flipping \`published\` is the cutover.
insert into public.hh_sites (slug, name, hostnames, template_key, published, config) values (
  ${q(site.slug)},
  ${q(site.name)},
  ${q('{' + (site.hostnames || []).join(',') + '}')},
  ${q(site.template_key)},
  false,
  $json$${json}$json$::jsonb
)
on conflict (slug) do update
  set name         = excluded.name,
      hostnames    = excluded.hostnames,
      template_key = excluded.template_key,
      config       = excluded.config,
      updated_at   = now();`);
} else {
  console.error('usage: node to-builder.mjs catalogue|seed');
  process.exit(1);
}
